name: Build Android APK on Tag

on:
  push:
    tags:
      'v?(uat|prd)-\\d+\\.\\d+\\.\\d+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker context
        run: echo "DOCKER_BUILDKIT=1" >> .dockerfile
      - name: Login to GitHub Container Registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      - name: Use ghcr.io/leapkh/android-ci:1.0.1 image
        uses: actions/setup-docker-image@v1
        with:
          image: ghcr.io/leapkh/android-ci:1.0.1
      - name: Make build script executable
        run: chmod +x ./../../scripts/build_script.sh
      - name: Build APK
        run: ./../../scripts/build_script.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: TaskUnity.apk
          path: TaskUnity.apk
