name: Deploy on Tag

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your deployment steps or commands here
      - name: Deploy
        run: |
          # Your deployment commands go here
          echo "Deploying from tag: ${{ github.ref }}"
